import { Router } from "express";
import transcribeRouter from "./transcribe";
import chatRouter from "./chat";
import speakRouter from "./speak";
import conversationsRouter from "./conversations";
import settingsRouter from "./settings";
import memoriesRouter from "./memories";
import gmailRouter from "./gmail";
import spotifyRouter from "./spotify";
import browseRouter from "./browse";
import generateImageRouter from "./generate-image";
import codeRouter from "./code";
import researchRouter from "./research";
import bookRouter from "./book";
import pushRouter from "./push";
import llmKeysRouter from "./llm-keys";
import terminalRouter from "./terminal";
import verifyRouter from "./verify";
import secretsRouter from "./secrets";
import timersRouter from "./timers";
import projectsRouter from "./projects";
import groupsRouter from "./groups";
import buildRouter from "./build";
import hotReloadRouter from "./hot-reload";
import packageManagerRouter from "./package-manager";
import gitRouter from "./git";
import searchRouter from "./search";
import debugRouter from "./debug";
import testRouter from "./test";
import collabRouter from "./collab";
import templatesRouter from "./templates";
import communityTemplatesRouter from "./community-templates";
import dockerRouter from "./docker";
import databaseRouter from "./database";
import apiExplorerRouter from "./api-explorer";
import shortcutsRouter from "./shortcuts";
import exportRouter from "./export";
import importRouter from "./import";
import historyRouter from "./history";
import e2eRouter from "./e2e";
import performanceRouter from "./performance";
import securityRouter from "./security";
import accessibilityRouter from "./accessibility";
import compatibilityRouter from "./compatibility";
import envManagerRouter from "./env-manager";
import configWizardRouter from "./config-wizard";
import migrationsRouter from "./migrations";
import packageEditorRouter from "./package-editor";

const router = Router();

router.use(conversationsRouter);
router.use(settingsRouter);
router.use(memoriesRouter);
router.use(transcribeRouter);
router.use(chatRouter);
router.use(speakRouter);
router.use(gmailRouter);
router.use(spotifyRouter);
router.use("/browse", browseRouter);
router.use(generateImageRouter);
router.use(codeRouter);
router.use(researchRouter);
router.use(bookRouter);
router.use(pushRouter);
router.use(llmKeysRouter);
router.use(secretsRouter);
router.use(terminalRouter);
router.use(verifyRouter);
router.use(timersRouter);
router.use(projectsRouter);
router.use(groupsRouter);
router.use(buildRouter);
router.use(hotReloadRouter);
router.use(packageManagerRouter);
router.use(gitRouter);
router.use(searchRouter);
router.use(debugRouter);
router.use(testRouter);
router.use(collabRouter);
router.use(templatesRouter);
router.use(communityTemplatesRouter);
router.use(dockerRouter);
router.use(databaseRouter);
router.use(apiExplorerRouter);
router.use(shortcutsRouter);
router.use(exportRouter);
router.use(importRouter);
router.use(historyRouter);
router.use(e2eRouter);
router.use(performanceRouter);
router.use(securityRouter);
router.use(accessibilityRouter);
router.use(compatibilityRouter);
router.use(envManagerRouter);
router.use(configWizardRouter);
router.use(migrationsRouter);
router.use(packageEditorRouter);

export default router;
