import { Router } from "express";
import authRouter from "./auth";
import transcribeRouter from "./transcribe";
import chatRouter from "./chat";
import speakRouter from "./speak";
import conversationsRouter from "./conversations";
import settingsRouter from "./settings";
import memoriesRouter from "./memories";
import projectMemoriesRouter from "./project-memories";
import projectInstructionsRouter from "./project-instructions";
import projectTasksRouter from "./project-tasks";
import projectResearchRouter from "./project-research";
import projectActivityRouter from "./project-activity";
import gmailRouter from "./gmail";
import spotifyRouter from "./spotify";
import browseRouter from "./browse";
import generateImageRouter from "./generate-image";
import codeRouter from "./code";
import researchRouter from "./research";
import bookRouter from "./book";
import pushRouter from "./push";
import llmKeysRouter from "./llm-keys";
import terminalRouter from "./terminal";
import verifyRouter from "./verify";
import secretsRouter from "./secrets";
import timersRouter from "./timers";
import projectsRouter from "./projects";
import groupsRouter from "./groups";
import buildRouter from "./build";
import buildCheckpointsRouter from "./build-checkpoints";
import buildTelemetryRouter from "./build-telemetry";
import buildExportRouter from "./build-export";
import buildSchedulesRouter from "./build-schedules";
import hotReloadRouter from "./hot-reload";
import packageManagerRouter from "./package-manager";
import gitRouter from "./git";
import searchRouter from "./search";
import debugRouter from "./debug";
import testRouter from "./test";
import collabRouter from "./collab";
import templatesRouter from "./templates";
import communityTemplatesRouter from "./community-templates";
import dockerRouter from "./docker";
import databaseRouter from "./database";
import apiExplorerRouter from "./api-explorer";
import shortcutsRouter from "./shortcuts";
import exportRouter from "./export";
import importRouter from "./import";
import historyRouter from "./history";
import e2eRouter from "./e2e";
import performanceRouter from "./performance";
import securityRouter from "./security";
import accessibilityRouter from "./accessibility";
import compatibilityRouter from "./compatibility";
import envManagerRouter from "./env-manager";
import configWizardRouter from "./config-wizard";
import migrationsRouter from "./migrations";
import packageEditorRouter from "./package-editor";
import extensionRouter, { handleExtensionUpgrade } from "./extension";
import apiKeysRouter from "./api-keys";
import connectorsRouter from "./connectors";
import selfEvolutionRouter from "./self-evolution";
import mapsRouter from "./maps";
import projectTypesRouter from "./project-types";
import companyToolsRouter from "./company-tools";

const router = Router();

router.use(authRouter);
router.use(apiKeysRouter);
router.use(connectorsRouter);
router.use(selfEvolutionRouter);
router.use(mapsRouter);
router.use(projectTypesRouter);
router.use(companyToolsRouter);
router.use(conversationsRouter);
router.use(settingsRouter);
// Mount before the global memory router so scoped /memories/:id mutations can
// handle requests that include projectId, while requests without it fall through.
router.use(projectMemoriesRouter);
router.use(memoriesRouter);
router.use(transcribeRouter);
router.use(chatRouter);
router.use(speakRouter);
router.use(gmailRouter);
router.use(spotifyRouter);
router.use("/browse", browseRouter);
router.use(generateImageRouter);
router.use(codeRouter);
router.use(researchRouter);
router.use(bookRouter);
router.use(pushRouter);
router.use(llmKeysRouter);
router.use(secretsRouter);
router.use(terminalRouter);
router.use(verifyRouter);
router.use(timersRouter);
router.use(projectInstructionsRouter);
router.use(projectTasksRouter);
router.use(projectResearchRouter);
router.use(projectActivityRouter);
router.use(projectsRouter);
router.use(groupsRouter);
router.use(buildRouter);
router.use(buildCheckpointsRouter);
router.use(buildTelemetryRouter);
router.use(buildExportRouter);
router.use(buildSchedulesRouter);
router.use(hotReloadRouter);
router.use(packageManagerRouter);
router.use(gitRouter);
router.use(searchRouter);
router.use(debugRouter);
router.use(testRouter);
router.use(collabRouter);
router.use(templatesRouter);
router.use(communityTemplatesRouter);
router.use(dockerRouter);
router.use(databaseRouter);
router.use(apiExplorerRouter);
router.use(shortcutsRouter);
router.use(exportRouter);
router.use(importRouter);
router.use(historyRouter);
router.use(e2eRouter);
router.use(performanceRouter);
router.use(securityRouter);
router.use(accessibilityRouter);
router.use(compatibilityRouter);
router.use(envManagerRouter);
router.use(configWizardRouter);
router.use(migrationsRouter);
router.use(packageEditorRouter);
router.use(extensionRouter);

export { handleExtensionUpgrade };
export default router;
